users:
  - name: Kevin NZUGUEM
    login: k.nzuguem
    email: kevin.nzuguem@nzuguem.me
    is_admin: true
  - name: Michelle MOCHE
    login: m.moche
    email: michelle.moche@nzuguem.me
  - name: Idriss TAYO
    login: i.tayo
    email: idriss.tayo@nzuguem.me
  - name: Team 1 TECH
    login: t1.tech
    email: t1.tech@nzuguem.me
  - name: Team 2 TECH
    login: t2.tech
    email: t2.tech@nzuguem.me

groups:
  - name: team-1
    description: Team 1
    members:
      - k.nzuguem
      - m.moche
      - t1.tech
    template:
      name: Team 1 Projects
      description: Team 1 Projects
      project_key_pattern: me.nzuguem.team-1.*
    roles:
      admins: 
      - k.nzuguem
      tech: t1.tech
  - name: team-2
    description: Team 2
    members:
      - k.nzuguem
      - i.tayo
      - t2.tech
    template:
      name: Team 2 Projects
      description: Team 2 Projects
      project_key_pattern: me.nzuguem.team-2.*
    roles:
      admins: 
      - k.nzuguem
      tech: t2.tech